from base.com.controller import area_controller
from base.com.controller import complain_controller
from base.com.controller import dataset_controller
from base.com.controller import disease_controller
from base.com.controller import feedback_controller
from base.com.controller import home_controller
from base.com.controller import login_controller
from base.com.controller import specialist_controller
from base.com.controller import user_controller
from base.com.controller import classification_controller
from base.com.controller import appointment_controller
